from __future__ import annotations

import hashlib
import time
import uuid
from dataclasses import dataclass
from typing import Any

from app.capabilities.models import (
    Capability,
    CapabilityRequest,
)


@dataclass
class PaymentRequest:
    """
    Represents an x402 payment requirement generated by the backend.
    """

    payment_id: str
    capability_id: str
    amount: float
    currency: str
    blockchain: str
    recipient: str
    expires_at: int

    def to_dict(self) -> dict[str, Any]:
        return {
            "payment_id": self.payment_id,
            "capability_id": self.capability_id,
            "amount": self.amount,
            "currency": self.currency,
            "blockchain": self.blockchain,
            "recipient": self.recipient,
            "expires_at": self.expires_at,
        }


class X402Client:
    """
    x402 payment client.

    The capability layer calls this class whenever a paid capability
    is selected.

    The implementation is deliberately isolated here so the rest of
    the application does not need to know payment protocol details.

    Flow:

        Agent
          ↓
        Capability Client
          ↓
        X402 Client
          ↓
        Payment requirement
          ↓
        Payment proof
          ↓
        Facilitator
          ↓
        Algorand settlement
    """

    def __init__(
        self,
        *,
        recipient: str | None = None,
        network: str = "algorand-testnet",
        timeout: int = 300,
    ) -> None:
        self.recipient = recipient or ""
        self.network = network
        self.timeout = timeout

    # ------------------------------------------------------------------
    # CREATE PAYMENT
    # ------------------------------------------------------------------

    def create_payment(
        self,
        capability: Capability,
        request: CapabilityRequest,
    ) -> dict[str, Any]:
        """
        Create an x402 payment requirement.

        The actual blockchain settlement is handled by
        app/payments/facilitator.py and app/payments/algorand.py.
        """

        if not capability.is_paid():
            return {
                "success": True,
                "payment_required": False,
            }

        if not capability.requires_x402():
            return {
                "success": False,
                "error": (
                    "Paid capability is not configured "
                    "to use x402."
                ),
            }

        if not capability.requires_algorand():
            return {
                "success": False,
                "error": (
                    "Paid x402 capability must use "
                    "Algorand settlement."
                ),
            }

        payment = self.build_payment_request(
            capability=capability,
            request=request,
        )

        return {
            "success": True,
            "payment_required": True,
            "payment_id": payment.payment_id,
            "payment_request": payment.to_dict(),
        }

    # ------------------------------------------------------------------
    # BUILD PAYMENT REQUEST
    # ------------------------------------------------------------------

    def build_payment_request(
        self,
        capability: Capability,
        request: CapabilityRequest,
    ) -> PaymentRequest:
        """
        Build the payment requirement that can be presented to the
        client/frontend.
        """

        payment_id = self._generate_payment_id(
            capability.id,
            request.task_id,
        )

        return PaymentRequest(
            payment_id=payment_id,
            capability_id=capability.id,
            amount=capability.price,
            currency=capability.currency,
            blockchain=(
                capability.blockchain.value
            ),
            recipient=self.recipient,
            expires_at=int(
                time.time()
                + self.timeout
            ),
        )

    # ------------------------------------------------------------------
    # VERIFY PAYMENT
    # ------------------------------------------------------------------

    def verify_payment(
        self,
        payment_proof: str,
        payment_request: PaymentRequest,
    ) -> dict[str, Any]:
        """
        Verify that a payment proof is present and structurally valid.

        Final blockchain verification is delegated to the facilitator
        and Algorand layers.
        """

        if not payment_proof:
            return {
                "success": False,
                "error": "Payment proof is missing.",
            }

        if (
            int(time.time())
            > payment_request.expires_at
        ):
            return {
                "success": False,
                "error": "Payment request has expired.",
            }

        return {
            "success": True,
            "payment_id": payment_request.payment_id,
            "payment_proof": payment_proof,
            "requires_settlement": True,
        }

    # ------------------------------------------------------------------
    # SETTLE
    # ------------------------------------------------------------------

    async def settle(
        self,
        payment_proof: str,
        payment_request: PaymentRequest,
    ) -> dict[str, Any]:
        """
        Send the verified payment to the facilitator for settlement.
        """

        verification = self.verify_payment(
            payment_proof,
            payment_request,
        )

        if not verification["success"]:
            return verification

        try:
            from app.payments.facilitator import (
                payment_facilitator,
            )

            result = payment_facilitator.settle(
                payment_proof=payment_proof,
                payment_request=payment_request,
            )

            if hasattr(result, "__await__"):
                result = await result

            if isinstance(result, dict):
                return result

            return {
                "success": bool(result),
                "payment_id": payment_request.payment_id,
            }

        except Exception as exc:
            return {
                "success": False,
                "payment_id": payment_request.payment_id,
                "error": str(exc),
            }

    # ------------------------------------------------------------------
    # PAYMENT ID
    # ------------------------------------------------------------------

    @staticmethod
    def _generate_payment_id(
        capability_id: str,
        task_id: str | None,
    ) -> str:
        """
        Generate a deterministic payment reference for a request.
        """

        raw = (
            f"{capability_id}:"
            f"{task_id or uuid.uuid4()}:"
            f"{time.time_ns()}"
        )

        digest = hashlib.sha256(
            raw.encode("utf-8")
        ).hexdigest()[:24]

        return f"x402_{digest}"

    # ------------------------------------------------------------------
    # HEALTH
    # ------------------------------------------------------------------

    def health(self) -> dict[str, Any]:
        """
        Return payment-client configuration status.
        """

        return {
            "protocol": "x402",
            "network": self.network,
            "recipient_configured": bool(
                self.recipient
            ),
            "timeout_seconds": self.timeout,
            "ready": bool(
                self.recipient
            ),
        }


# ----------------------------------------------------------------------
# GLOBAL CLIENT
# ----------------------------------------------------------------------

x402_client = X402Client()